#This file was originally generated by PyScripter's unitest wizard

import unittest
from crypt_heidisql import encrypt, decrypt

class TestGlobalFunctions(unittest.TestCase):

    def setUp(self):
        self.b_pass = '1234567890'
        self.c_pass = '38393a3b3c3d3e3f40377'

    def tearDown(self):
        del self.b_pass
        del self.c_pass

    def test_decrypt(self):
        self.assertEqual(decrypt(self.c_pass), self.b_pass)

    def test_encrypt_decrypt(self):
        self.assertEqual(decrypt(encrypt(self.b_pass)), self.b_pass)


if __name__ == '__main__':
    unittest.main()
