# -*- coding: utf-8 -*-

#This file was originally generated by PyScripter's unitest wizard

import unittest
from crypt_sqlyog import DecodePassword, EncodePassword

class TestGlobalFunctions(unittest.TestCase):
    def setUp(self):
        self.b_pass = '1234567890'
        self.c_pass = 'mBmZGpobmxycGA=='

    def tearDown(self):
        del self.b_pass
        del self.c_pass

    def testDecodePassword(self):
        self.assertEqual(DecodePassword(self.c_pass), self.b_pass)

    def testEncodePassword(self):
        self.assertEqual(EncodePassword(self.b_pass), self.c_pass)

    def testEncodeDecodePassword(self):
        self.assertEqual(DecodePassword(EncodePassword(self.b_pass)), self.b_pass)

    def testDecodeEncodePassword(self):
        self.assertEqual(EncodePassword(DecodePassword(self.c_pass)), self.c_pass)


if __name__ == '__main__':
    unittest.main()
